version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hms-mysql
    restart: always
    environment:
      MYSQL_DATABASE: hms_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis for Session / JWT Revocation
  redis:
    image: redis:7.0-alpine
    container_name: hms-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Elasticsearch for Doctor Search
  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: hms-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data



volumes:
  mysql-data:
  redis-data:
  es-data:
